### ISSUE TITLE
Set VINDPM bug

### ISSUE THREAD

**Issue by keith06388** [sqmsmu/PMIC_BQ25896#1]
Thanks for this library.  It also works with BQ25895 with a couple scale changes.  I found a small issue that wasn't letting me set VINDPM correctly, but fixed it as follows

in PMIC_BQ29896.cpp, line 604 should be:
temp_reg.vindpm = data;

**Comment by sqmsmu** [comment]
Thanks for that, I will fix the issue and update the release.
