### ISSUE TITLE
5v boost

### ISSUE THREAD

**Issue by smoochiee** [sqmsmu/PMIC_BQ25896#2]
whats code for boost to 5v ouput?

**Comment by sqmsmu** [comment]
// Boost (OTG) Mode Configuration
    // 0 – OTG Disable (default)
    // 1 – OTG Enable
    void setOTG_CONFIG(bool value);

Using this function. You need to set "otg_config" bit in "sys_ctrl_reg_t" register.
There are some other additional requirements to fulfil before turning OTG on. Refer to the datasheet for this.
